# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bme280.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'bme280.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62me280.proto\"\x8f\x01\n\x06\x42ME280\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\x11\n\tbeehiveid\x18\x02 \x02(\t\x12\x10\n\x08sensorid\x18\x03 \x02(\t\x12\x15\n\rtemperature_f\x18\x04 \x01(\x02\x12\x16\n\x0ehumidity_prcnt\x18\x05 \x01(\x02\x12\x1e\n\x16\x62\x61rometricpressure_hpa\x18\x06 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bme280_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BME280']._serialized_start=17
  _globals['_BME280']._serialized_end=160
# @@protoc_insertion_point(module_scope)
